apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo
  namespace: default
spec:
  dnsNames:
    - echo1.kubeshore.com
    - echo2.kubeshore.com
  secretName: echo-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer  