apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
  namespace: default
spec:
  dnsNames:
    - grafana.gckubie.com
  secretName: grafana-app-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer