apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: grafana
spec:
  tls:
  - hosts:
    - grafana.gckubie.com
    secretName: grafana-app-tls
  rules:
  - host: grafana.gckubie.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: grafana-np
            port: 
              number: 80